### ISSUE TITLE
An idea for knowing how many spaces are available in your trade target's inventory

### ISSUE THREAD

**Issue by llogical** [ThornyFFXI/Bellhop#3]
Please consider for future improvement: If the person that you are trading is in your whitelist for auto accepting a trade, having them send you an automated tell of the remaining inventory spaces available would be very helpful when trading multiple items multiple times.
Just an idea, thank you so much.

**Comment by ThornyFFXI** [comment]
This sort of feature seems intended for automation or afk usage, which is not really the intent of the plugin.  It also has potential to be detected by square enix, since the tells would go through server in a consistant format.  As a result, I will not be adding this feature.
